version: "3.9"

services:
    nginx:
      build:
        context: .
        dockerfile: .docker/local/nginx/Dockerfile
      depends_on:
        - api
        - auth
    api:
      build:
          context: .
          dockerfile: ./.docker/api/Dockerfile
      ports:
        - "8070:8070"
      image: "api"
      container_name: "api"
      depends_on:
        - redis
        - postgres
    auth:
      build:
          context: .
          dockerfile: ./.docker/auth/Dockerfile
      image: "auth"
      container_name: "auth"
      ports:
        - "8080:8080"
      depends_on:
        - redis
        - postgres
    postgres:
      build:
          context: .
          dockerfile: .docker/postgresql/Dockerfile
      ports: 
          - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      image: ${POSTGRES_NAME}
      container_name: ${POSTGRES_NAME}
      environment:
          - PGDATA=${POSTGRES_DATA}
          - POSTGRES_DB=${POSTGRES_DB}
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    redis:
      build:
          context: .
          dockerfile: .docker/redis/Dockerfile
      ports:
          - "${REDIS_PORT}:6379"
      image: ${REDIS_NAME}
      container_name: ${REDIS_NAME}
